# Generated by Django 3.1.4 on 2020-12-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mamazon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripton',
            new_name='description',
        ),
    ]
